#!/bin/sh
# postinst script for monitoring-to-redmine-notify

set -e

cd /usr/share/monitoring-to-redmine-notify

if [ -f composer.lock ] ; then
    rm composer.lock
fi

composer --no-dev -o update

#DEBHELPER#

exit 0
